/** This class is used for defining constants values of dashboard. */
export class DashboardConstants {
    NAN_SAMPLES = -123456789;
}

export const GEO_MAP_GROUP_ID = [10210, 10215, 107, 3, 4, 6];
export const GEO_MAP_EXTENDED_GROUP_ID = [10267, 10456, 107];
export const GEO_MAP_GRAPH_ID = 3;
export const usaStateMap = {
    'Alabama': 'countries/us/us-al-all',
    'Alaska': 'countries/us/us-ak-all',
    'Arizona': 'countries/us/us-az-all',
    'Arkansas': 'countries/us/us-ar-all',
    'California': 'countries/us/us-ca-all',
    'Colorado': 'countries/us/us-co-all',
    'Delaware': 'countries/us/us-de-all',
    'District of Columbia': 'countries/us/us-dc-all',
    'Florida': 'countries/us/us-fl-all',
    'Georgia': 'countries/us/us-ga-all',
    'Hawaii': 'countries/us/us-hi-all',
    'Idaho': 'countries/us/us-id-all',
    'Illinois': 'countries/us/us-il-all',
    'Indiana': 'countries/us/us-in-all',
    'Iowa': 'countries/us/us-ia-all',
    'Kansas': 'countries/us/us-ks-all',
    'Kentucky': 'countries/us/us-ky-all',
    'Louisiana': 'countries/us/us-la-all',
    'Maine': 'countries/us/us-me-all',
    'Maryland': 'countries/us/us-md-all',
    'Massachusetts': 'countries/us/us-ma-all',
    'Michigan': 'countries/us/us-mi-all',
    'Minnesota': 'countries/us/us-mn-all',
    'Mississippi': 'countries/us/us-ms-all',
    'Missouri': 'countries/us/us-mo-all',
    'Montana': 'countries/us/us-mt-all',
    'Nebraska': 'countries/us/us-ne-all',
    'Nevada': 'countries/us/us-nv-all',
    'New Hampshire': 'countries/us/us-nh-all',
    'NewHampshire': 'countries/us/us-nh-all',
    'New Jersey': 'countries/us/us-nj-all',
    'NewJersey': 'countries/us/us-nj-all',
    'New Mexico': 'countries/us/us-nm-all',
    'NewMexico': 'countries/us/us-nm-all',
    'NewYork': 'countries/us/us-ny-all',
    'New York': 'countries/us/us-ny-all',
    'NorthCarolina': 'countries/us/us-nc-all',
    'North Carolina': 'countries/us/us-nc-all',
    'NorthDakota': 'countries/us/us-nd-all',
    'North Dakota': 'countries/us/us-nd-all',
    'Ohio': 'countries/us/us-oh-all',
    'Oklahoma': 'countries/us/us-ok-all',
    'Oregon': 'countries/us/us-or-all',
    'Pennsylvania': 'countries/us/us-pa-all',
    'Rhode Island': 'countries/us/us-ri-all',
    'RhodeIsland': 'countries/us/us-ri-all',
    'SouthCarolina': 'countries/us/us-sc-all',
    'South Carolina': 'countries/us/us-sc-all',
    'SouthDakota': 'countries/us/us-sd-all',
    'South Dakota': 'countries/us/us-sd-all',
    'Tennessee': 'countries/us/us-tn-all',
    'Texas': 'countries/us/us-tx-all',
    'Utah': 'countries/us/us-ut-all',
    'Vermont': 'countries/us/us-vt-all',
    'Virginia': 'countries/us/us-va-all',
    'Washington': 'countries/us/us-wa-all',
    'WestVirginia': 'countries/us/us-wv-all',
    'West Virginia': 'countries/us/us-wv-all',
    'Wisconsin': 'countries/us/us-wi-all',
    'Wyoming': 'countries/us/us-wy-all'
};