export class ChartxAxis {
    allowDecimals = true;
    alternateGridColor: string = null;
    breaks: any;
    categories: any;
    crosshair = { width: 1, color: 'black' };
    dateTimeLabelFormats: any;
    events: any;
    floor = 0;
    gridLineDashStyle = 'Solid';
    gridLineWidth = 1;
    gridZIndex = 1;
    labels: any;
    lineWidth = 1;
    minorGridLineDashStyle = 'Solid';
    minorGridLineWidth = 1;
    minorTickLength = 2;
    minorTickPosition = 'outside';
    minorTickWidth = 0;
    nameToX = true;
    offset = 0;
    opposite = false;
    plotBands: any;
    plotLines: any;
    reversed = false;
    showEmpty = true;
    showFirstLabel = true;
    showLastLabel = true;
    startOnTick = false;
    tickLength = 10;
    tickPosition = 'outside';
    tickWidth = 1;
    title: any = {};
    type = 'linear';
    visible = true;
    tickPositions: number[];
    gridLineColor = '#525151'; //'#5A6F89';
    tickmarkPlacement: any;
  }